// ─── WealthWise AI – Memory Architecture ─────────────────────────────────────
//
// Three-layer memory model:
//   Layer 1: Permanent DB  — structured user data, never expires
//   Layer 2: Summarized    — AI-generated long-term behavioral profile
//   Layer 3: Session       — ephemeral within one conversation

// ─── Layer 1: Permanent Storage (PostgreSQL / Prisma) ────────────────────────
// Stored in the database. Managed by the application, not the AI.

export interface PermanentUserMemory {
  // Identity & demographics (from onboarding)
  userId: string;
  name: string;
  age: number;
  occupation: string;
  riskProfile: string;
  investmentExperience: string;
  country: string;
  currency: string;

  // Financial snapshot — updated monthly
  monthlyIncome: number;
  monthlyExpenses: number;
  savingsRate: number;
  emergencyFundMonths: number;
  netWorth: number;
  financialHealthScore: number;
  healthGrade: string;

  // Goals — updated per user action
  goals: StoredGoal[];

  // Portfolio — synced from connected accounts or manual entry
  portfolioSummary: StoredPortfolioSummary;

  // Loans & Insurance — updated per user action
  loans: StoredLoan[];
  insurancePolicies: StoredInsurance[];

  // Behavioral history — append-only, useful for trend analysis
  monthlyReviewHistory: MonthlyReviewRecord[];
  healthScoreHistory: HealthScoreRecord[];

  // Subscription
  subscriptionPlan: string;
  subscriptionExpiresAt: string;

  createdAt: string;
  updatedAt: string;
}

export interface StoredGoal {
  id: string;
  name: string;
  category: string;
  targetAmount: number;
  currentAmount: number;
  targetDate: string;
  monthlySIPRequired: number;
  priority: string;
  status: string;
  lastUpdated: string;
}

export interface StoredPortfolioSummary {
  totalValue: number;
  totalInvested: number;
  overallGainLossPercent: number;
  assetAllocation: Record<string, number>;
  lastSyncedAt: string;
}

export interface StoredLoan {
  type: string;
  outstandingAmount: number;
  monthlyEmi: number;
  interestRate: number;
  remainingMonths: number;
}

export interface StoredInsurance {
  type: string;
  coverAmount: number;
  annualPremium: number;
}

export interface MonthlyReviewRecord {
  month: string;
  savingsRate: number;
  totalIncome: number;
  totalSaved: number;
  totalInvested: number;
  healthScore: number;
}

export interface HealthScoreRecord {
  date: string;
  score: number;
  grade: string;
}

// ─── Layer 2: AI-Generated Long-Term Memory Summary ──────────────────────────
// Generated by AI after each session. Stored as text in DB.
// Injected into future conversations as context.
// Updated at end of each significant conversation (not every message).

export interface AIMemorySummary {
  userId: string;

  // Behavioral patterns the AI has observed
  financialPersonality: string;     // e.g. "risk-averse, disciplined saver, anxious about retirement"
  commonConcerns: string[];         // e.g. ["worried about job security", "unsure about NPS vs PPF"]
  financialStrengths: string[];     // e.g. ["consistent SIP investor", "no high-interest debt"]
  blindSpots: string[];             // e.g. ["no term insurance", "no ELSS for tax saving"]

  // Advice history summary
  topRecommendationsMade: string[]; // Last 5 key recommendations given
  goalsDiscussed: string[];         // Which goals have been analyzed
  topicsToRevisit: string[];        // Things the user wanted to come back to

  // Communication preferences learned
  preferredResponseStyle: 'detailed' | 'concise' | 'visual';
  financialLiteracyLevel: 'basic' | 'intermediate' | 'advanced';
  preferredLanguage: string;        // e.g. "Hindi terms mixed with English"

  // Last session context
  lastSessionDate: string;
  lastSessionSummary: string;       // 2-3 sentence summary of last conversation
  pendingFollowUps: string[];       // Things to ask/revisit next session

  generatedAt: string;
}

// Prompt to generate the memory summary at end of session
export const MEMORY_SUMMARIZER_PROMPT = `
You are summarizing a financial advisory conversation for long-term memory storage.

Based on the conversation provided, extract and update the following memory fields.
Be concise — this summary will be injected into future conversations, so prioritize
what will make the AI advisor more personalized and effective next time.

Focus on:
1. What financial personality traits did the user demonstrate? (anxious, disciplined, impulsive, etc.)
2. What are their main concerns, fears, or hopes about money?
3. What key advice was given? Did the user accept or push back?
4. What topics were left incomplete or should be revisited?
5. What is their financial literacy level based on the questions asked?
6. Any important life events mentioned (job change, marriage, baby, bonus)?

Output ONLY valid JSON matching the AIMemorySummary schema (omit userId, generatedAt — system fills these).
`.trim();

// ─── Layer 3: Session Memory (in-memory, not persisted) ──────────────────────
// Lives only for the duration of a conversation. Injected into each message.
// Used to maintain coherence within a multi-turn conversation.

export interface SessionMemoryStore {
  sessionId: string;
  userId: string;
  startedAt: string;

  // Conversation state
  messagesInSession: number;
  topicsDiscussed: string[];
  recommendationsMade: string[];

  // User state in this session
  currentMood: 'positive' | 'neutral' | 'anxious' | 'confused' | 'frustrated';
  questionsAsked: string[];

  // What the AI has already told them (to avoid repetition)
  alreadyCoveredWarnings: string[];   // e.g. "already warned about no emergency fund"
  alreadySuggestedActions: string[];  // e.g. "already suggested increasing SIP by 5k"

  // Temporary calculation cache
  calculationsPerformed: Record<string, unknown>;

  // Feature flags for this session
  isNewUser: boolean;
  isPremiumUser: boolean;
}

// ─── Memory Update Strategy ───────────────────────────────────────────────────

export const MEMORY_UPDATE_RULES = {
  // Update permanent DB when:
  triggerPermanentUpdate: [
    'user updates income or expenses',
    'user adds or completes a goal',
    'user reports a new loan or pays off a loan',
    'user updates portfolio (manual entry or sync)',
    'monthly review is completed',
    'financial health score is recalculated',
    'subscription plan changes',
  ],

  // Regenerate AI memory summary when:
  triggerMemorySummaryUpdate: [
    'conversation has 5+ turns',
    'significant new financial information shared',
    'user mentions a life event (job change, marriage, etc.)',
    'recommendation was accepted or rejected',
    '30+ days since last summary generation',
  ],

  // Session memory lives only in:
  sessionStorage: 'Redis with 2-hour TTL per session',

  // Never store in memory:
  neverStore: [
    'exact account numbers or card details',
    'OTPs or passwords',
    'raw transaction data (only aggregated summaries)',
    'sensitive documents',
  ],
} as const;

// ─── Memory Injection Helper ──────────────────────────────────────────────────

export function formatMemoryForInjection(memory: AIMemorySummary): string {
  return `
## Long-Term Memory — What I Know About You

**Your Financial Personality:** ${memory.financialPersonality}

**Your Key Strengths:** ${memory.financialStrengths.join(', ')}

**Areas I've Flagged Previously:** ${memory.blindSpots.join(', ')}

**Your Main Concerns:** ${memory.commonConcerns.join(', ')}

**Last Time We Spoke (${memory.lastSessionDate}):** ${memory.lastSessionSummary}

**Things to Follow Up On:** ${memory.pendingFollowUps.join(', ')}
`.trim();
}
